apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot.fullname" . }}-config
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
data:
  instructions.md: |
{{ .Values.config.instructionsMd | indent 4 }}
  settings.yaml: |
{{ .Values.config.settingsYaml | indent 4 }}
